- hosts: rails
  gather_facts: no
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
    - name: Download https://github.com/lwwwr/sample-rails-hw.git
      git: 
        repo: "https://github.com/lwwwr/sample-rails-hw.git"
        dest: lab
        accept_hostkey: yes
        force: true
    - name: bundle install
      become: true  
      become_user: ubuntu
      command: bash -lc "bundle install"
      args:
        chdir: "/home/ubuntu/lab"   
    - name: access for a normal yarn installation
      become: true
      become_user: ubuntu
      command: bash -lc "sudo chmod -R 777 ."
      args:
        chdir: "/home/ubuntu/lab"  
    - name: Puma Stop
      become: true  
      become_user: ubuntu
      command: bash -lc "bundle exec pumactl -F config/puma.rb stop"
      args:
        chdir: "/home/ubuntu/lab"
      ignore_errors: true      

    - name: rails s
      become: true  
      become_user: ubuntu
      command: bash -lc "rails s -p 3003 -b 0.0.0.0"
      args:
        chdir: "/home/ubuntu/lab"
      
        
        
